// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoDismissController from "./auto_dismiss_controller"
import LoadingButtonController from "./loading_button_controller"
import PlaidLinkController from "./plaid_link_controller"
import PullToRefreshController from "./pull_to_refresh_controller"

application.register("auto-dismiss", AutoDismissController)
application.register("loading-button", LoadingButtonController)
application.register("plaid-link", PlaidLinkController)
application.register("pull-to-refresh", PullToRefreshController)
