plugins:
  - rubocop-rails

require:
  - rubocop-capybara

AllCops:
  NewCops: enable

Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
Layout/LineLength:
  Max: 500

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
