plugins:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Enabled: false
