plugins:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRailsVersion: 8.1
  MigratedSchemaVersion: '20260205082205'
  NewCops: enable

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/ClassAndModuleChildren:                                                                                                                            
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
