plugins:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
