spring.application.name=paychecq

spring.datasource.url=jdbc:postgresql://localhost:5432/paychecq_development
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoint.health.enabled=true
management.endpoint.health.show-details=when_authorized

spring.flyway.locations=db/migrations/{vendor}

spring.jackson.time-zone=UTC