package com.douglasrlee.paychecq.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Indicates that the annotated element is generated by a tool. This will also exclude the type/method/constructor from code coverage.
 * This annotation can be applied to types, methods, or constructors.
 */
@Retention(RUNTIME)
@Target({TYPE, METHOD, CONSTRUCTOR})
public @interface Generated { }
