default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: paychecq_development
    username: admin
    password: password
    host: localhost
    port: 5432
  solid:
    <<: *primary_development
    migrations_paths: db/solid_migrate
    database: paychecq_development_solid

test:
  primary: &primary_test
    <<: *default
    database: paychecq_test
    username: admin
    password: password
    host: localhost
    port: 5432
  solid:
    <<: *primary_test
    migrations_paths: db/solid_migrate
    database: paychecq_test_solid

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["PAYCHECQ_PRIMARY_DATABASE_URL"] %>
  solid:
    <<: *primary_production
    migrations_paths: db/solid_migrate
    url: <%= ENV["PAYCHECQ_SOLID_DATABASE_URL"] %>
