default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: paychecq_development
    username: admin
    password: password
    host: localhost
    port: 5432
  solid:
    <<: *primary_development
    database: paychecq_solid_development
    migrations_paths: db/solid_migrate

test:
  primary: &primary_development
    <<: *default
    database: paychecq_test
    username: admin
    password: password
    host: localhost
    port: 5432
  solid:
    <<: *primary_development
    database: paychecq_solid_test
    username: admin
    password: password
    host: localhost
    port: 5432
    migrations_paths: db/solid_migrate

production:
  primary: &primary_production
    <<: *default
  solid:
    <<: *primary_production
    migrations_paths: db/solid_migrate
