name: Java Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup OpenJDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23'
          cache: 'maven'

      - name: Maven Test
        run: mvn test
