name: Java Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Java Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: paychecq_development
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup OpenJDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23'
          cache: 'maven'

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready --username=testuser --dbname=testdb --host=localhost --port=5432; do
            >&2 echo "Postgres is unavailable - sleeping"
            sleep 1
          done
          >&2 echo "Postgres is up - executing command"

      - name: Maven Test
        run: mvn test

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
