name: Ruby Checks

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    name: Scan Ruby
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for ruby vulnerabilities
        run: bin/brakeman --no-pager

  scan_js:
    name: Scan JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for javascript vulnerabilities
        run: bin/importmap audit

  lint:
    name: Lint Ruby
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint ruby
        run: bin/rubocop -f github

